spring:
  application:
    name: kanban
  http:
    log-request-details: true
  datasource:
    url: jdbc:mysql://localhost/kanban_app
    username: root
    password:
    # Configuration pools de connection
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 900000 # Equals to 15min
  resources:
    add-mappings: false

info:
  application:
    name: kanban
    version: G01R00C00
server:
  port: 20370

management:
  server:
    port: 21370
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - restart
          - info
          - metrics
          - health
          - shutdown

config:
  property: CeciEstLaValeurDeLaPropriete
java:
  runtime:
    version: 11