spring:
  application:
    name: kanban-app
  datasource:
    url: jdbc:mysql://localhost/sir_tp
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

info:
  application:
    name: kanban-app
    version: G01R00C00
server:
  port: 18999

logging:
  config: src\main\resources\logback\logback-spring-dev.xml
  outputPath: _LOG

management:
  server:
    port: 16999
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - restart
          - info
          - metrics
          - health
          - shutdown
          - prometheus
          - chaosmonkey